/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package takeaway.challenge;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;

public class TakeawayTest {
    @Test public void ReturnsNameAndPrice() {
        MenuItem Dish = new MenuItem("Chicken korma", 5.99);
        assertEquals("returns the name", String.valueOf("Chicken korma"), Dish.GetDishName());
        assertEquals("returns the price", Double.valueOf(5.99), Dish.GetDishPrice());
    }

    @Test public void AddsDishesToMenu() {
        TakeawayMenu Menu = new TakeawayMenu();
        MenuItem KormaDish = new MenuItem("Chicken korma", 5.99);
        MenuItem TikkaMasalaDish = new MenuItem("Prawn tikka masala", 5.89);
        Menu.AddToMenu(KormaDish);
        Menu.AddToMenu(TikkaMasalaDish);
        ArrayList<takeaway.challenge.MenuItem> TestMenu = new ArrayList<>();
        TestMenu.add(KormaDish);
        TestMenu.add(TikkaMasalaDish);
        assertEquals("returns the menu with two dishes", TestMenu, Menu.ViewMenu());
    }
}
