/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package takeaway.challenge;

import java.util.ArrayList;

public class CustomerOrder {
    ArrayList<takeaway.challenge.MenuItem> Order = new ArrayList<>();

    public void AddToOrder(MenuItem Dish) {
        Order.add(Dish);
    }

    public ArrayList ViewOrder() {
        return Order;
    }

    public boolean CheckPrice(Double ExpectedPrice) {
        Double ActualPrice = 0.00;
        for (MenuItem Dish : Order) {
            ActualPrice += Dish.GetDishPrice();
        }
        Double ActualPriceRounded = Math.round(ActualPrice * 100.0) / 100.0;
        if (ActualPriceRounded.equals(ExpectedPrice)) {
            return true;
        } else {
            return false;
        }
    }

}
