/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package takeaway.challenge;

import java.util.ArrayList;

public class CustomerOrder {
    ArrayList<takeaway.challenge.MenuItem> Order = new ArrayList<>();

    public void AddToOrder(MenuItem Dish) {
        Order.add(Dish);
    }

    public ArrayList ViewOrder() {
        return Order;
    }

}
