/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package takeaway.challenge;

public class MenuItem {
    String DishName;
    Double DishPrice;

    public MenuItem(String name, Double price) {
        DishName = name;
        DishPrice = price;
    }
    
    public String GetDishName() {
        return DishName;
    }

    public Double GetDishPrice() {
        return DishPrice;
    }
}