/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package takeaway.challenge;

import java.util.ArrayList;

public class TakeawayMenu {
    ArrayList<Class> Menu = new ArrayList<>();

    public void AddToMenu(Class Dish) {
        Menu.add(Dish);
    }

    public ArrayList ViewMenu() {
        return Menu;
    }
}
